// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATkYjrKLMuKcrCS4RnpuWvAblZuoT40mA',
    appId: '1:765895487459:web:58cf503b60acc39d85fad6',
    messagingSenderId: '765895487459',
    projectId: 'peach-hub-16c86',
    authDomain: 'peach-hub-16c86.firebaseapp.com',
    storageBucket: 'peach-hub-16c86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LiUJ_RH5zO6MdFiQfEK-xMKgfbU_ZpM',
    appId: '1:765895487459:android:018ef8ca3aa9aacc85fad6',
    messagingSenderId: '765895487459',
    projectId: 'peach-hub-16c86',
    storageBucket: 'peach-hub-16c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTtsm4UzPGSR-2n3dDc--q4RofQFvgHFA',
    appId: '1:765895487459:ios:346892ebf1f4291385fad6',
    messagingSenderId: '765895487459',
    projectId: 'peach-hub-16c86',
    storageBucket: 'peach-hub-16c86.appspot.com',
    iosBundleId: 'love.peachhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTtsm4UzPGSR-2n3dDc--q4RofQFvgHFA',
    appId: '1:765895487459:ios:346892ebf1f4291385fad6',
    messagingSenderId: '765895487459',
    projectId: 'peach-hub-16c86',
    storageBucket: 'peach-hub-16c86.appspot.com',
    iosBundleId: 'love.peachhub.app',
  );
}
